### ISSUE TITLE
任务百科游戏接口

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/wiki#22]
现在我们的map是直接用的静态json
直接对线上的map表提供一套接口。
注意添加缓存，目的是要对任务百科的侧边栏的地图做成树菜单。
实际上地图是存在TYPE分类的

![f8322e9deff86d237dab2844db4994e4](https://github.com/JX3BOX/wiki/assets/8476969/2496b882-1944-4b71-8cbf-e2bf029276dc)

![ca583b058d5c1dffec905d8f230a9d5e](https://github.com/JX3BOX/wiki/assets/8476969/fba14b28-bb5a-414e-ac3e-9cd2ed47fab6)

将接口回复在楼下即可

- [x] 已完成

**Comment by x3zvawq** [comment]
https://node.jx3box.com/api/node/quest/maps
