### ISSUE TITLE
成就杂项

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/wiki#33]
## 统计

侧边栏统计数量和游戏内保持一致
具体推进南宫伯比对，找出原因

- [x] 已完成

**Comment by iRuxu** [comment]
## 目录

https://www.jx3box.com/cj/1
一级分类需要显示成就

如果确认接口正常请求了，则让牧野完善前端即可

- [x] 已完成

**Comment by x3zvawq** [comment]
> ## 统计
> 侧边栏统计数量和游戏内保持一致 具体推进南宫伯比对，找出原因
> 
> * [ ]  已完成

游戏里成就数量统计有些奇怪，他的上限6767不知道是哪来的，因为右边目录加起来就只有6240
![image](https://github.com/JX3BOX/wiki/assets/47066861/d6b8df3e-7d96-416f-a8db-8526b21fc236)

![image](https://github.com/JX3BOX/wiki/assets/47066861/14289bf3-77aa-4d5b-ba3d-421b9301c595)

但是已完成的数量可以由右边目录的已完成数量加起来得到
然后目前网站的问题在于，menus接口返回的 会带上当前目录下的所有成就id
但是游戏里分阶段的成就，比如传功
![image](https://github.com/JX3BOX/wiki/assets/47066861/cb9e2e7e-34d5-486b-bf2b-3295ca893be0)

他是要全部完成才会把这个成就标记为完成的，而之前接口只会返回系列成就的第一项，所以目前网站的判断不太准
所以我改了一下接口，现在/api/node/achievement/menus这个接口每个分类下的achievements以及子分类下的achievements数组，里面的成就如果是普通成就（即不用分阶段的）会是一个number，如果是阶段成就则会是一个数组，数组内是这个成就的所有阶段

![image](https://github.com/JX3BOX/wiki/assets/47066861/db0aac57-4807-42fd-b7f2-9bfcdedb4c88)

只有这个数组内的所有项目都完成，才可以判断这个成就是完成的，才可以计入成就完成数。
这么操作应该可以保证网站内的已完成成就数和游戏内的对应上，但是上限目前尚且不知道游戏内是怎么拿到的
所以我寻思先计算出一个 网站统计的6630和游戏内统计的6767的差值 137 然后以后固定加上这个？

**Comment by fifthThirteen** [comment]
![image](https://github.com/JX3BOX/wiki/assets/30660189/befa0b26-344a-46bc-9c15-40518e8be470)
阶段成就已改为只有当数组内最后一项已完成时，menus统计才会计算完成。
总完成成就是独立的，算的是所有成就完成，但是是在menus的总完成成就里面过滤出来的，以menus的为基准，游戏内上报的只作为过滤的依据。

- [x] 已了解
