### ISSUE TITLE
成就同步异常

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/wiki#34]
## 角色头像

<img width="459" alt="image" src="https://github.com/JX3BOX/wiki/assets/8476969/b54e2d3b-9483-4c45-8da3-02ae4a24599e">

## 角色缓存

<img width="384" alt="image" src="https://github.com/JX3BOX/wiki/assets/8476969/4fc93b9f-d8f7-42eb-bbe7-b1568b0a342b">

---
![image](https://github.com/JX3BOX/wiki/assets/30660189/68638380-cfdb-4bd5-8ecf-cb2ced06750a)
线上的，应该是你本地没有在storage里面设置avatar

角色列表的storage去掉了，但是当前角色保留了storage，方便刷新继续留存

- [x] 已完成

**Comment by iRuxu** [comment]
## 角色切换

<img width="342" alt="image" src="https://github.com/JX3BOX/wiki/assets/8476969/c52ec484-56af-4193-8b2d-c9ea85484983">

切换没有任何反应

- [x] 已完成

**Comment by iRuxu** [comment]
## 只看未完成

<img width="419" alt="image" src="https://github.com/JX3BOX/wiki/assets/8476969/c866facb-8b71-4a6d-9ac7-c57b6ee9498c">

也没反应

- [x] 已完成

**Comment by iRuxu** [comment]
## 统计数

统计问题请推进不咕
业务上一些游戏表问题可让南宫伯协同去弄

- [x] 已完成

**Comment by iRuxu** [comment]
## 单页
<img width="1919" alt="image" src="https://github.com/JX3BOX/wiki/assets/8476969/d1b125bf-03ca-4a75-8387-d65faa399c07">

- [x] 已完成

**Comment by fifthThirteen** [comment]
![image](https://github.com/JX3BOX/wiki/assets/30660189/fe3774b8-ec8c-4406-8124-55ab21a08c0c)
阶段成就修改：
1. 虚拟角色成就 单个single的设为完成及取消完成改为阶段批量修改。
2. 只有全部完成才会显示已完成，有一个未完成则显示未完成。
3. 虚拟角色支持阶段成就中单个成就的完成与取消。
4. 虚拟角色全选时会包含阶段成就的子成就了。
5. 侧边栏统计完成只会判断最后一阶段成就是否完成（主要用于游戏角色的判断，适配游戏内的显示）。
6. 已确定游戏内的完成数只计算阶段成就的最后一阶段完成的那个成就。
7. 因总数统计是根据menu来的，所以区分了常规成就和五甲成就，所以将统计放到切换下面了，且统计数在其他板块下不再显示。
![image](https://github.com/JX3BOX/wiki/assets/30660189/089a0ef5-6447-4efd-9ec6-5e9364e093d8)

- [x] 已完成

**Comment by fifthThirteen** [comment]
角色切换和只看未完成我这边是一直可以的呀，线上和本地都可以。
