### ISSUE TITLE
物价接口替换

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/wiki#38]
<img width="541" alt="image" src="https://github.com/user-attachments/assets/7653b9c4-71d2-4362-a907-71ae88abdcc1">

**Comment by iRuxu** [comment]
百科中的 https://www.jx3box.com/item/view/5_24428

- [x] 已完成

**Comment by iRuxu** [comment]
pvx中的
https://www.jx3box.com/pvg/price
https://www.jx3box.com/pvg/price?tab=goods

- [x] 已完成

**Comment by iRuxu** [comment]
商城的支付等待2s，随便搞个css loading先

- [x] 已完成

**Comment by fifthThirteen** [comment]
pvg 物价&我的关注优化
